id: AE872FDD0
title: Essence of All the Buddhas of Past, Present and Future
type: translation
pechas:
- IB106D455
- I3B679A94
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:31:06.014034
  last_modified_at: 2023-01-04 11:31:06.014045
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  IB106D455/8454: C412
  I3B679A94/2D3D: C412
